---
- name: Playbook to setup the environment
  hosts: all

  tasks:

    # WSL configuration

    - name: Set up wsl.conf
      become: true
      ansible.builtin.template:
        src: wsl.conf.j2
        dest: /etc/wsl.conf
        owner: root
        group: root
        mode: '0644'

    # Pacman configuration

    - name: Configure pacman options for better usability and faster performance
      become: true
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        insertafter: '^\[options\]'
        regexp: '^#?\s*{{ item.option }}\s*=?.*$'
        line: "{{ item.option }}{{ ' = ' + item.value if item.value is defined else '' }}"
        state: present
      loop:
        - { option: 'Color' }
        - { option: 'VerbosePkgLists' }
        - { option: 'ParallelDownloads', value: '24' }
        - { option: 'ILoveCandy' }
      loop_control:
        label: "{{ item.option }}"

    # Makepkg configuration

    - name: Configure makepkg.conf for faster builds
      become: true
      ansible.builtin.lineinfile:
        path: /etc/makepkg.conf
        regexp: '^#?\s*{{ item.option }}\s*=?.*$'
        line: '{{ item.option }}{{ item.value }}'
        state: present
      loop:
        - { option: 'CFLAGS=', value: '"-march=native -mtune=native -O2 -pipe -fno-plt -fexceptions \' }
        - { option: 'MAKEFLAGS=', value: '"-j$(nproc)"' }
        - { option: 'OPTIONS=', value: '(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)' }
        - { option: 'PKGEXT=', value: '".pkg.tar"' }
      loop_control:
        label: "{{ item.option }}"

    # Locale configuration

    - name: Configure system locale settings
      become: true
      block:
        - name: Generate and enable the specified locale
          community.general.locale_gen:
            name: "{{ locale }}"
            state: present

        - name: Check current system locale configuration
          ansible.builtin.shell:
            cmd: |
              set -o pipefail
              localectl status | grep "System Locale: LANG={{ locale }}"
          register: locale_status
          failed_when: false
          changed_when: false

        - name: Apply locale as system default
          ansible.builtin.shell:
            cmd: >
              localectl set-locale "{{ locale }}"
          when: locale_status.rc != 0
          changed_when: locale_status.rc != 0

    # Enable time synchronization

    - name: Configure time synchronization on WSL
      become: true
      block:
        - name: Create the systemd-timesyncd override directory
          ansible.builtin.file:
            path: "/etc/systemd/system/systemd-timesyncd.service.d"
            state: directory
            mode: '0755'

        - name: Create systemd-timesyncd override configuration
          ansible.builtin.template:
            src: systemd-timesyncd-override.conf.j2
            dest: "/etc/systemd/system/systemd-timesyncd.service.d/override.conf"
            owner: "root"
            group: "root"
            mode: '0644'

    # Package installation

    - name: Install useful packages
      aur:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - less
          - nano
          - unzip
          - man
          - mc
          - bash-completion
          - openssh
          - keychain
          - jq
          - pwgen
          - whois
          - strace
          - tcpdump
          - eza
          - procs
          - zoxide
          - starship
          - bat
          - dog
          - ripgrep
          - github-cli
          - aws-cli-v2
          - aws-vault
          - postgresql
          - docker
          - docker-buildx
          - docker-compose
          - tenv-bin
          - kubectl
          - kubectx
          - k9s
          - helm
          - amazon-corretto-21-bin
          - amazon-corretto-17
          - mesa
          - mesa-utils
          - vulkan-dzn

    # Configuration

    - name: Create the ~/.config directory
      ansible.builtin.file:
        path: "/home/{{ username }}/.config"
        state: directory
        mode: '0750'

    # nano configuration

    - name: Configure nano
      block:
        - name: Install nano-syntax-highlighting
          aur:
            name: nano-syntax-highlighting
            state: present

        - name: Create the ~/.config/nano directory
          ansible.builtin.file:
            path: "/home/{{ username }}/.config/nano"
            state: directory
            mode: '0750'

        - name: Set up the user-specific nano configuration file
          ansible.builtin.copy:
            src: /etc/nanorc
            dest: "/home/{{ username }}/.config/nano/nanorc"
            mode: '0640'
            force: false

        - name: Add syntax-highlighting to the configuration file
          ansible.builtin.blockinfile:
            path: "/home/{{ username }}/.config/nano/nanorc"
            block: |
              include "/usr/share/nano/*.nanorc"
              include "/usr/share/nano-syntax-highlighting/*.nanorc"

    # procs configuration

    - name: Configure procs
      block:
        - name: Create the ~/.config/procs directory
          ansible.builtin.file:
            path: /home/{{ username }}/.config/procs
            state: directory
            mode: '0750'

        - name: Configure procs
          ansible.builtin.template:
            src: procs.toml.j2
            dest: "/home/{{ username }}/.config/procs/config.toml"
            owner: "{{ username }}"
            group: "{{ username }}"
            mode: '0640'

    # starship configuration

    - name: Configure starship
      ansible.builtin.template:
        src: starship.toml.j2
        dest: "/home/{{ username }}/.config/starship.toml"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0640'

    # git configuration

    - name: Set up .gitconfig
      ansible.builtin.template:
        src: .gitconfig.j2
        dest: "/home/{{ username }}/.gitconfig"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'

    # Java configuration

    - name: Configure Java environment
      block:

        - name: Get the default JDK
          ansible.builtin.shell:
            cmd: >
              archlinux-java get
          register: result_jdk_status
          changed_when: false

        - name: Set the default JDK
          become: true
          ansible.builtin.shell:
            cmd: >
              archlinux-java set java-21-amazon-corretto
          when: result_jdk_status.stdout is defined and result_jdk_status.stdout | length == 0
          changed_when: true

    # Terraform configuration

    - name: Configure Terraform environment
      block:
        - name: Check if terraform is already installed
          ansible.builtin.shell:
            cmd: >
              tenv tf list
          register: result_tenv_tf_status
          changed_when: false

        - name: Install terraform
          ansible.builtin.shell:
            cmd: >
              tenv tf install
          when: result_tenv_tf_status.stdout is defined and result_tenv_tf_status.stdout | length == 0
          changed_when: true

        - name: Check if tofu is already installed
          ansible.builtin.shell:
            cmd: >
              tenv tofu list
          register: result_tenv_tofu_status
          changed_when: false

        - name: Install tofu
          ansible.builtin.shell:
            cmd: >
              tenv tofu install
          when: result_tenv_tofu_status.stdout is defined and result_tenv_tofu_status.stdout | length == 0
          changed_when: true

    # Docker configuration

    - name: Add the user to the docker group
      become: true
      ansible.builtin.user:
        name: "{{ username }}"
        groups: docker
        append: true

    - name: Start docker and automatically start it on boot
      become: true
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    # 1Password configuration

    - name: Import GPG key for 1password-cli
      ansible.builtin.shell: |
        if ! gpg --list-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22; then
          gpg --recv-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
        fi
      changed_when: false

    - name: Install 1password-cli and some helper scripts
      block:
        - name: Install 1password-cli
          aur:
            name: "1password-cli"
            state: present

        - name: Create the ~/.aws directory
          ansible.builtin.file:
            path: "/home/{{ username }}/.aws"
            state: directory
            mode: '0750'

        - name: Install AWS MFA credentials helper script (uses 1password-cli and aws-vault)
          ansible.builtin.template:
            src: aws_credentials.sh.j2
            dest: "/home/{{ username }}/.aws/aws_credentials.sh"
            owner: "{{ username }}"
            group: "{{ username }}"
            mode: '0750'

    # bashrc configuration

    - name: Set up .bashrc
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/home/{{ username }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0640'
      with_fileglob:
        - templates/.bashrc*.j2
